ALTER TYPE "KycCaseStatus" ADD VALUE IF NOT EXISTS 'SEF_DECISION_PENDING';
ALTER TYPE "KycCaseStatus" ADD VALUE IF NOT EXISTS 'SEF_DECISION_IN_PROGRESS';
ALTER TYPE "KycCaseStatus" ADD VALUE IF NOT EXISTS 'SEF_APPROVED';
ALTER TYPE "KycCaseStatus" ADD VALUE IF NOT EXISTS 'SEF_REJECTED';

ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SEF_TASK_ASSIGNED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SEF_DECISION_COMPLETED';

ALTER TYPE "ReviewStage" ADD VALUE IF NOT EXISTS 'SEF';

ALTER TYPE "ReviewDecision" ADD VALUE IF NOT EXISTS 'SEND_TO_SEF';
