const kycStatusLabels: Record<string, string> = {
  INQUIRY_RECEIVED: 'INQUIRY RECEIVED',
  PROPOSAL_OPTIONAL: 'PROPOSAL OPTIONAL',
  LEGAL_DOCUMENTS_PENDING: 'DOCUMENTS REQUIRED FOR KYC PREPARATION PENDING',
  LEGAL_DOCUMENTS_UPLOADED: 'DOCUMENTS REQUIRED FOR KYC PREPARATION UPLOADED',
  SUBMITTED_TO_AML: 'SUBMITTED FOR APPROVAL',
  AML_REVIEW_STARTED: 'APPROVAL REVIEW STARTED',
  SUPERVISOR_REVIEW_PENDING: 'AML SUPERVISOR REVIEW PENDING',
  SUPERVISOR_REVIEW_IN_PROGRESS: 'AML SUPERVISOR REVIEW IN PROGRESS',
  SUPERVISOR_ADDITIONAL_INFORMATION_REQUIRED: 'AML SUPERVISOR ADDITIONAL INFORMATION REQUIRED',
  SUPERVISOR_REVIEW_COMPLETED: 'AML SUPERVISOR REVIEW COMPLETED',
  DMLRO_REVIEW_PENDING: 'DMLRO REVIEW PENDING',
  DMLRO_REVIEW_IN_PROGRESS: 'DMLRO REVIEW IN PROGRESS',
  DMLRO_ADDITIONAL_INFORMATION_REQUIRED: 'DMLRO ADDITIONAL INFORMATION REQUIRED',
  DMLRO_REVIEW_COMPLETED: 'DMLRO REVIEW COMPLETED',
  MLRO_REVIEW_PENDING: 'MLRO REVIEW PENDING',
  MLRO_REVIEW_IN_PROGRESS: 'MLRO REVIEW IN PROGRESS',
  MLRO_ADDITIONAL_INFORMATION_REQUIRED: 'MLRO ADDITIONAL INFORMATION REQUIRED',
  MLRO_APPROVED: 'MLRO APPROVED',
  MLRO_APPROVED_WITH_CONDITIONS: 'MLRO APPROVED WITH CONDITIONS',
  MLRO_REJECTED: 'MLRO REJECTED',
  SEF_DECISION_PENDING: 'SEF DECISION PENDING',
  SEF_DECISION_IN_PROGRESS: 'SEF DECISION IN PROGRESS',
  SEF_APPROVED: 'SEF APPROVED',
  SEF_REJECTED: 'SEF REJECTED',
  FINAL_SIGNATURES_PENDING: 'FINAL SIGNATURES PENDING',
  FINAL_DOCUMENTS_PENDING: 'FINAL DOCUMENTS PENDING',
  KYC_FINAL_APPROVED: 'KYC FINAL APPROVED',
  CLIENT_ACTIVATION_PENDING: 'CLIENT ACTIVATION PENDING',
  CLIENT_ACTIVE: 'CLIENT ACTIVE',
  CLIENT_REJECTED: 'CLIENT REJECTED',
  CLIENT_ON_HOLD: 'CLIENT ON HOLD'
};

export function kycStatusLabel(value: string) {
  return kycStatusLabels[value] || value.split('_').join(' ');
}
