const kycStatusLabels: Record<string, string> = {
  INQUIRY_RECEIVED: 'INQUIRY RECEIVED',
  PROPOSAL_OPTIONAL: 'PROPOSAL OPTIONAL',
  LEGAL_DOCUMENTS_PENDING: 'DOCUMENTS REQUIRED FOR KYC PREPARATION PENDING',
  LEGAL_DOCUMENTS_UPLOADED: 'DOCUMENTS REQUIRED FOR KYC PREPARATION UPLOADED',
  SUBMITTED_TO_AML: 'SUBMITTED TO AML',
  AML_REVIEW_STARTED: 'AML REVIEW STARTED'
};

export function kycStatusLabel(value: string) {
  return kycStatusLabels[value] || value.split('_').join(' ');
}
